package zedly.zenchantments;

import zedly.zenchantments.enchantments.*;

public class ZenchantmentClassStorage {

    public static final Class<? extends Zenchantment>[] LIST = new Class[]{
        Anthropomorphism.class,
        Apocalypse.class,
        Arborist.class,
        Bind.class,
        Blanket.class,
        BlazesCurse.class,
        Blizzard.class,
        Bounce.class,
        Burst.class,
        Combustion.class,
        Caffeine.class,
        Chitin.class,
        Conversion.class,
        Decapitation.class,
        Ethereal.class,
        Fire.class,
        Firestorm.class,
        Fireworks.class,
        Force.class,
        Fuse.class,
        Germination.class,
        Glide.class,
        Gluttony.class,
        GoldRush.class,
        Grab.class,
        GreenThumb.class,
        Harvest.class,
        Haste.class,
        HelpingHand.class,
        IceAspect.class,
        Jump.class,
        Laser.class,
        Level.class,
        LongCast.class,
        Lumber.class,
        Magnetism.class,
        MasterKey.class,
        Meador.class,
        Missile.class,
        Mow.class,
        MysteryFish.class,
        NetherStep.class,
        NightVision.class,
        Persephone.class,
        Pierce.class,
        Plough.class,
        Potion.class,
        PotionResistance.class,
        Quake.class,
        QuickShot.class,
        Rainbow.class,
        RainbowSlam.class,
        Reaper.class,
        Reveal.class,
        Saturation.class,
        ShortCast.class,
        Shred.class,
        Singularity.class,
        Siphon.class,
        SonicShock.class,
        Spectral.class,
        Speed.class,
        Spikes.class,
        Stationary.class,
        Stock.class,
        Stream.class,
        Switch.class,
        Terraformer.class,
        Toxic.class,
        Tracer.class,
        Transformation.class,
        Trough.class,
        Unrepairable.class,
        Variety.class,
        Vortex.class,
        Weight.class
    };

}
