ZenchantmentsConfigVersion: 1.5.2

# probability: (Decimal) (0 = no probability, -1 = disabled)
#    Chance of obtaining the enchantment when enchanting

# tools: (Axe, Shovel, Sword, Pickaxe, Rod, Shears, Bow, Lighter,
#            Hoe, Helmet, Chestplate, Leggings, Boots, Elytra, All)
#    Determines what tools can recieve the enchantment

# name: (For color use the Paragraph symbol '?' instead of "&")
#    Determines the appearance of the enchantment on tools

# max-level: (Integer)
#    Determines the highest obtainable level for the enchantment

# cooldown (Integer) (In increments of 1/20th of a second)
#    Determines how quickly a user can repeatedly use the enchantment.
#    Note: Some enchantments cause bugs if you set it to 0.

# power (Decimal)
#    Determines how powerful the enchantments is

enchantments:
      # Regular Enchantments
      - Anthropomorphism:
              probability: 5.0
              tools: Pickaxe
              name: Anthropomorphism
              max-level: 1
              cooldown: 0
              power: 1.0
      - Arborist:
              probability: 4.0
              tools: Hoe
              name: Arborist
              max-level: 3
              cooldown: 0
              power: 1.0
      - Bind:
              probability: 0.0
              tools: All
              name: Bind
              max-level: 1
              cooldown: 0
              power: 1.0
      - Blanket:
              probability: 3.0
              tools: Axe, Shovel, Sword, Pickaxe, Hoe
              name: Blanket
              max-level: 3
              cooldown: 0
              power: 1.0
      - BlazesCurse:
              probability: 4.0
              tools: Chestplate
              name: Blaze's Curse
              max-level: 1
              cooldown: 0
              power: 1.0
      - Blizzard:
              probability: 4.0
              tools: Bow, Trident
              name: Blizzard
              max-level: 3
              cooldown: 0
              power: 1.0
      - Bounce:
              probability: 6.0
              tools: Boots
              name: Bounce
              max-level: 5
              cooldown: 0
              power: 1.0
      - Burst:
              probability: 1.0
              tools: Bow
              name: Burst
              max-level: 5
              cooldown: 0
              power: 2.0
      - Caffeine:
              probability: 4.0
              tools: Helmet
              name: Caffeine
              max-level: 3
              cooldown: 0
              power: 1.0
      - Chitin:
              probability: 5.0
              tools: Elytra
              name: Chitin
              max-level: 4
              cooldown: 0
              power: 1.0
      - Combustion:
              probability: 5.0
              tools: Chestplate
              name: Combustion
              max-level: 4
              cooldown: 0
              power: 1.0
      - Conversion:
              probability: 6.0
              tools: Sword
              name: Conversion
              max-level: 1
              cooldown: 0
              power: 1.0
      - Decapitation:
              probability: 6.0
              tools: Sword
              name: Decapitation
              max-level: 4
              cooldown: 0
              power: 1.0
      - Fire:
              probability: 4.0
              tools: Pickaxe, Shovel, Axe
              name: Fire
              max-level: 1
              cooldown: 0
              power: 1.0
      - Firestorm:
              probability: 5.0
              tools: Bow, Trident
              name: Firestorm
              max-level: 3
              cooldown: 0
              power: 1.0
      - Fireworks:
              probability: 6.0
              tools: Bow, Trident
              name: Fireworks
              max-level: 4
              cooldown: 0
              power: 1.0
      - Force:
              probability: 4.0
              tools: Sword
              name: Force
              max-level: 3
              cooldown: 0
              power: 1.0
      - Fuse:
              probability: 6.0
              tools: Bow, Trident
              name: Fuse
              max-level: 1
              cooldown: 0
              power: 1.0
      - Germination:
              probability: 4.0
              tools: Hoe
              name: Germination
              max-level: 3
              cooldown: 0
              power: 1.0
      - Glide:
              probability: 3.0
              tools: Leggings
              name: Glide
              max-level: 3
              cooldown: 0
              power: 1.0
      - Gluttony:
              probability: 5.0
              tools: Helmet
              name: Gluttony
              max-level: 1
              cooldown: 0
              power: 1.0
      - GoldRush:
              probability: 5.0
              tools: Shovel
              name: Gold Rush
              max-level: 3
              cooldown: 0
              power: 1.0
      - Grab:
              probability: 5.0
              tools: Pickaxe, Shovel, Axe
              name: Grab
              max-level: 1
              cooldown: 0
              power: 1.0
      - GreenThumb:
              probability: 5.0
              tools: Leggings
              name: Green Thumb
              max-level: 3
              cooldown: 0
              power: 1.0
      - Harvest:
              probability: 4.0
              tools: Hoe
              name: Harvest
              max-level: 3
              cooldown: 0
              power: 1.0
      - Haste:
              probability: 0.0
              tools: Pickaxe, Shovel, Axe
              name: Haste
              max-level: 4
              cooldown: 0
              power: 1.0
      - HelpingHand:
              probability: 3.0
              tools: Chestplate
              name: Helping Hand
              max-level: 1
              cooldown: 0
              power: 1.0
      - IceAspect:
              probability: 6.0
              tools: Sword, Trident
              name: Ice Aspect
              max-level: 2
              cooldown: 0
              power: 1.0
      - Jump:
              probability: 4.0
              tools: Boots
              name: Jump
              max-level: 4
              cooldown: 0
              power: 1.0
      - Laser:
              probability: 1.0
              tools: Pickaxe, Axe
              name: Laser
              max-level: 3
              cooldown: 0
              power: 1.0
      - Level:
              probability: 4.0
              tools: Bow, Sword, Pickaxe, Trident
              name: Level
              max-level: 3
              cooldown: 0
              power: 1.0
      - LongCast:
              probability: 5.0
              tools: Rod
              name: Long Cast
              max-level: 2
              cooldown: 0
              power: 1.0
      - Lumber:
              probability: 1.0
              tools: Axe
              name: Lumber
              max-level: 1
              cooldown: 0
              power: 1.0
      - Magnetism:
              probability: 4.0
              tools: Leggings
              name: Magnetism
              max-level: 1
              cooldown: 0
              power: 1.0
      - MasterKey:
              probability: 4.0
              tools: Chestplate
              name: Master Key
              max-level: 1
              cooldown: 0
              power: 1.0
      - Meador:
              probability: 1.0
              tools: Boots
              name: Meador
              max-level: 1
              cooldown: 0
              power: 1.0
      - Mow:
              probability: 4.0
              tools: Shears
              name: Mow
              max-level: 1
              cooldown: 0
              power: 1.0
      - MysteryFish:
              probability: 2.0
              tools: Rod
              name: Mystery Fish
              max-level: 1
              cooldown: 0
              power: 10.0
      - NetherStep:
              probability: 1.0
              tools: Boots
              name: Nether Step
              max-level: 3
              cooldown: 0
              power: 1.0
      - NightVision:
              probability: 2.0
              tools: Helmet
              name: Night Vision
              max-level: 1
              cooldown: 0
              power: 1.0
      - Persephone:
              probability: 4.0
              tools: Hoe
              name: Persephone
              max-level: 3
              cooldown: 0
              power: 1.0
      - Pierce:
              probability: 3.0
              tools: Pickaxe
              name: Pierce
              max-level: 1
              cooldown: 0
              power: 1.0
      - Plough:
              probability: 4.0
              tools: Hoe
              name: Plough
              max-level: 3
              cooldown: 0
              power: 1.0
      - Potion:
              probability: 5.0
              tools: Bow, Trident
              name: Potion
              max-level: 3
              cooldown: 0
              power: 1.0
      - PotionResistance:
              probability: 6.0
              tools: Helmet, Chestplate, Leggings, Boots
              name: Potion Resistance
              max-level: 4
              cooldown: 0
              power: 1.0
      - QuickShot:
              probability: 2.0
              tools: Bow, Trident
              name: Quick Shot
              max-level: 1
              cooldown: 0
              power: 1.0
      - Rainbow:
              probability: 3.0
              tools: Shears
              name: Rainbow
              max-level: 1
              cooldown: 0
              power: 1.0
      - RainbowSlam:
              probability: 5.0
              tools: Sword
              name: Rainbow Slam
              max-level: 4
              cooldown: 0
              power: 1.0
      - Reaper:
              probability: 4.0
              tools: Bow, Sword, Trident
              name: Reaper
              max-level: 4
              cooldown: 0
              power: 1.0
      - Reveal:
              probability: 0.0
              tools: Pickaxe
              name: Reveal
              max-level: 4
              cooldown: 0
              power: 1.0
      - Saturation:
              probability: 2.0
              tools: Leggings
              name: Saturation
              max-level: 3
              cooldown: 0
              power: 1.0
      - ShortCast:
              probability: 4.0
              tools: Rod
              name: Short Cast
              max-level: 2
              cooldown: 0
              power: 1.0
      - Shred:
              probability: 1.0
              tools: Pickaxe, Shovel
              name: Shred
              max-level: 5
              cooldown: 0
              power: 1.0
      - Siphon:
              probability: 3.0
              tools: Sword, Bow, Trident
              name: Siphon
              max-level: 4
              cooldown: 0
              power: 1.0
      - SonicShock:
              probability: 2.0
              tools: Elytra
              name: Sonic Shock
              max-level: 3
              cooldown: 0
              power: 1.0
      - Spectral:
              probability: 0.0
              tools: Shovel
              name: Spectral
              max-level: 1
              cooldown: 0
              power: 1.0
      - Speed:
              probability: 3.0
              tools: Boots
              name: Speed
              max-level: 4
              cooldown: 0
              power: 1.0
      - Spikes:
              probability: 5.0
              tools: Boots
              name: Spikes
              max-level: 3
              cooldown: 0
              power: 1.0
      - Stationary:
              probability: 5.0
              tools: Bow, Sword, Trident
              name: Stationary
              max-level: 1
              cooldown: 0
              power: 1.0
      - Stock:
              probability: 5.0
              tools: Chestplate
              name: Stock
              max-level: 1
              cooldown: 0
              power: 1.0
      - Stream:
              probability: 3.0
              tools: Elytra
              max-level: 1
              name: Stream
              cooldown: 0
              power: 1.0
      - Switch:
              probability: 1.0
              tools: Pickaxe
              name: Switch
              max-level: 1
              cooldown: 1
              power: 1.0
      - Terraformer:
              probability: 2.0
              tools: Shovel
              name: Terraformer
              max-level: 1
              cooldown: 20
              power: 1.0
      - Toxic:
              probability: 0.0
              tools: Bow, Sword, Trident
              name: Toxic
              max-level: 4
              cooldown: 0
              power: 1.0
      - Tracer:
              probability: 1.0
              tools: Bow, Trident
              name: Tracer
              max-level: 4
              cooldown: 0
              power: 1.0
      - Transformation:
              probability: 5.0
              tools: Sword
              name: Transformation
              max-level: 3
              cooldown: 0
              power: 1.0
      - Trough:
              probability: 5.0
              tools: Chestplate, Leggings
              name: Trough
              max-level: 1
              cooldown: 0
              power: 1.0
      - Variety:
              probability: 4.0
              tools: Axe, Hoe
              name: Variety
              max-level: 1
              cooldown: 0
              power: 1.0
      - Vortex:
              probability: 6.0
              tools: Sword, Bow, Trident
              name: Vortex
              max-level: 1
              cooldown: 0
              power: 1.0
      - Weight:
              probability: 6.0
              tools: Boots
              name: Weight
              max-level: 4
              cooldown: 0
              power: 1.0
      # Admin Enchantments
      - Apocalypse:
              probability: 0.0
              tools: Bow, Trident
              name: Apocalypse
              max-level: 1
              cooldown: 0
              power: 1.0
      - Ethereal:
              probability: 0.0
              tools: All
              name: Ethereal
              max-level: 1
              cooldown: 0
              power: 1.0
      - Missile:
              probability: 0.0
              tools: Bow
              name: Missile
              max-level: 1
              cooldown: 0
              power: 1.0
      - Singularity:
              probability: 0.0
              tools: Bow, Trident
              name: Singularity
              max-level: 1
              cooldown: 0
              power: 1.0
      - Unrepairable:
              probability: 0.0
              tools: All
              name: Unrepairable
              max-level: 1
              cooldown: 0
              power: 1.0
# New Enchantments

#  Changes the overall probability of obtaining all custom enchantments
enchant-rarity: 60.0

#  Changes the maximum number of custom enchantments possible per item
max-enchants: 2

#  Determines what the Shred enchantment drops (all, block (no ores), or none)
shred-drops: block

#  Determines if the certain enchantments can break blocks
explosion-block-break: false

#  Determines if the enchantment descriptions show up in lore
description-lore : true

#  Fix old enchantment descriptions
fix-legacy-description-lore : false

#  Determines the color of enchantment descriptions shown in lore
description-color: a

#  Determines if enchantment glow is added by default even without vanilla enchantments.
#  (Set to false if you have issues with the HIDE_ENCHANTMENTS flag resetting)
enchantment-glow: true

#  Determines the color for enchantment lore
enchantment-color: 7

#  Determines the color for curse lore
curse-color: c
